# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @tokyo-night-tmux_theme night            # night | storm | moon | day
set -g @tokyo-night-tmux_transparent 1          # 1 = transparent | 0 = solid (default)
set -g @tokyo-night-tmux_show_datetime 1        # 1 = enabled (default) | 0 = disabled
set -g @tokyo-night-tmux_date_format hide       # hide | YMD | DMY | MDY
set -g @tokyo-night-tmux_time_format 24H        # hide | 12H | 24H
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g status-position top
set -g detach-on-destroy off

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

#bind-key -n A-S-Left swap-window -t -1
#bind-key -n A-S-Right swap-window -t +1

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key c new-window -c '#{pane_current_path}'
bind-key '"' split-window -c '#{pane_current_path}'
bind-key % split-window -h -c '#{pane_current_path}'

bind-key & kill-window
bind-key x kill-pane

#set-option -g default-command "reattach-to-user-namespace -l $SHELL"

set-option -g history-limit 5000

bind -N "last-session (via sesh) " b run-shell "sesh last"
bind a run-shell "sesh connect dotfiles"
bind o run-shell "sesh connect notes"
bind e run-shell "sesh connect cmus"
unbind i
bind i run-shell "sesh connect coversheet"
bind u run-shell "ghd"

bind-key "t" run-shell "sesh connect \"$(
 	sesh list | fzf-tmux -p 55%,60% \
    --no-sort --reverse --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' 
)\""

run '~/.tmux/plugins/tpm/tpm'
