#!/bin/bash
if [ "$2" = "up" ]; then
    if [ "$CONNECTION_UUID" = "ac9a0ac0-3dd4-45a2-a680-e8d7a8bd2546" ]; then
        squid_lht
    fi
elif [ "$2" = "vpn-up" ]; then
    if [ "$CONNECTION_UUID" = "eca3d62d-3664-4829-8ddf-1134130e302e" ]; then
        squid_lht
    fi
elif [ "$2" = "down" ]; then
    if [ "$CONNECTION_UUID" = "ac9a0ac0-3dd4-45a2-a680-e8d7a8bd2546" ]; then
        squid_default
    fi
elif [ "$2" = "vpn-down" ]; then
    if [ "$CONNECTION_UUID" = "eca3d62d-3664-4829-8ddf-1134130e302e" ]; then
        squid_default
    fi
fi
