#!/bin/bash
set -euxo pipefail

target_file="$1"

if [[ -f "$target_file" ]]; then
  echo "Already exists"
  exit 0
fi

echo "#!/bin/bash" >> "$target_file"
echo "set -euxo pipefail" >> "$target_file"
chmod +x "$target_file"

if [[ "$2" = "yadm" ]]; then
  yadm add "$target_file"
elif [[ "$2" = "doc" ]]; then
  setup_doc_dots
fi

nvim "$target_file"
