#!/bin/bash
wl-copy -f 01clear
wl-copy -f 02clear
wl-copy -f 03clear
wl-copy -f 04clear
wl-copy -f 05clear
wl-copy -f 06clear
wl-copy -f 07clear
wl-copy -f 08clear
wl-copy -f 09clear
wl-copy -f 10clear
wl-copy -f 11clear
wl-copy -f 12clear
wl-copy -f 13clear
wl-copy -f 14clear
wl-copy -f 15clear
