#!/usr/bin/env bash
SOURCE_MUS="/home/ole/music/"
CMUS_PL_DIR="/home/ole/.config/cmus/playlists"

mkdir -p "${CMUS_PL_DIR}"
rm -rf "${CMUS_PL_DIR}"
cp -r "${SOURCE_MUS}Playlists" "${CMUS_PL_DIR}"
find "${CMUS_PL_DIR}" -type f -iname '*.m3u' -exec sed -i 's/\.\.\//\/home\/ole\/music\//g' '{}' ';'
