#!/usr/bin/env bash
DROID_DIR="/home/ole/droid"
SOURCE_MUS="/home/ole/music/"
TARGET_MUS="${DROID_DIR}/SD card/Music/"
TARGET_AUDIOB="${DROID_DIR}/SD card/Audiobooks/"
CMUS_PL_DIR="/home/ole/.config/cmus/playlists"

mount_droid "$DROID_DIR"

if [[ -z $1 ]]; then
    FROM_DIR="${SOURCE_MUS}"
    TO_DIR="${TARGET_MUS}"
else
    FROM_DIR="${SOURCE_MUS}${1}/"
    TO_DIR="${TARGET_MUS}${1}/"
fi

if [[ -d "${FROM_DIR}" && -d "${TO_DIR}" ]]; then
    #LC_ALL=de_DE.ISO8859-1 rsync -rltDvP --update --delete --inplace --exclude=".*" "${FROM_DIR}" "${TO_DIR}"
    rsync -rltDvP --update --delete --inplace --exclude=".*" --exclude="/Audiobooks/" "${FROM_DIR}" "${TO_DIR}"
    rsync -rltDvP --update --delete --inplace --exclude=".*" "${FROM_DIR}Audiobooks/" "${TARGET_AUDIOB}"
else
    echo "Music dirs not found"
fi

umountrm "$DROID_DIR"
