#!/usr/bin/env bash
DROID_DIR="/home/ole/droid"
SOURCE_MUS="/home/ole/music/"
TARGET_MUS="${DROID_DIR}/SD card/Music/"
CMUS_PL_DIR="/home/ole/.config/cmus/playlists"

mount_droid "$DROID_DIR"

if [[ -z $1 ]]; then
    FROM_DIR="${SOURCE_MUS}"
    TO_DIR="${TARGET_MUS}"
else
    FROM_DIR="${SOURCE_MUS}${1}/"
    TO_DIR="${TARGET_MUS}${1}/"
fi

mkdir -p "${SOURCE_MUS}Playlists"
rm -rf "${SOURCE_MUS}Playlists"
cp -r "${CMUS_PL_DIR}" "${SOURCE_MUS}Playlists"
find "${SOURCE_MUS}Playlists" -type f -iname '*.m3u' -exec sed -i 's/\/home\/.*\/music/\.\./g' '{}' ';'

if [[ -d "${FROM_DIR}" && -d "${TO_DIR}" ]]; then
    #LC_ALL=de_DE.ISO8859-1 rsync -rltDvP --update --delete --inplace --exclude=".*" "${FROM_DIR}" "${TO_DIR}"
    rsync -rltDvP --update --delete --inplace --exclude=".*" "${FROM_DIR}" "${TO_DIR}"
else
    echo "Music dirs not found"
fi

umountrm "$DROID_DIR"
