#!/bin/bash
if uname -s | grep -q 'Darwin'; then
    RANUM=$(echo $RANDOM | head -c 1 ; echo '')
else
    RANUM=$(head /dev/urandom |  tr -dc 0-9 | head -c 1 ; echo '')
fi
PASSD=$(diceware -n 3 -d _)
echo "${PASSD}${RANUM}"
