#!/bin/bash
source ~/.config/dots/zshrc.local
note_dir=~/doc

cd ${note_dir}

result=$(w_ssh git pull && git add . && (git diff-index --quiet HEAD || git commit -m 'docsync') && w_ssh git push)

GIT_REMOTE_RESULT=$(git log HEAD..origin/main --oneline)
if [ ! -z "$(git status --porcelain)" ]; then 
  touch ~/.docsync_pending
elif [[ "${GIT_REMOTE_RESULT}" != "" ]] ; then
  touch ~/.docsync_pending
elif [[ -f ~/.docsync_pending ]]; then
  rm ~/.docsync_pending
fi

echo ${result}
