#!/bin/bash
if [ -z "$1" ]; then
  FEH_SEC=4
else
  FEH_SEC=$1
fi

if [ $# -eq 9 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
elif [ $# -eq 8 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4" "$5" "$6" "$7" "$8"
elif [ $# -eq 7 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4" "$5" "$6" "$7"
elif [ $# -eq 6 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4" "$5" "$6"
elif [ $# -eq 5 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4" "$5"
elif [ $# -eq 4 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3" "$4"
elif [ $# -eq 3 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2" "$3"
elif [ $# -eq 2 ]; then
  feh --auto-rotate -rZzxFYND $FEH_SEC "$2"
else
  feh --auto-rotate -rZzxFYND $FEH_SEC
fi
