#!/bin/bash
NAME=${1}
SUB_DIR=${2}

DIR=src/main/resources/db/migration
if [[ ${SUB_DIR} ]]; then
    DIR="${DIR}/${SUB_DIR}"
fi

if [[ -d ${DIR} ]]; then

    UNIXT=$(date +%s)
    FILENAME="V${UNIXT}__${NAME}.sql"
    touch "${DIR}/${FILENAME}"
fi
