#!/usr/bin/env bash
tmux new-session -d -s github_dash > /dev/null && tmux send-keys -t github_dash '(gitup -p > /dev/null & gh dash) && exit' Enter
if [[ "$1" != 'noattach' ]]; then
  sesh connect github_dash
fi
