#!/bin/bash
ZSH="${HOME}/.oh-my-zsh"
TARGET_PATH="/opt/oh-my-zsh"

if [[ -d "${TARGET_PATH}" ]]; then
    if [[ $1 == '--force' ]]; then
        sudo rm -rf ${TARGET_PATH}
    else
        exit 0
    fi
fi

echo installing oh my zsh

export KEEP_ZSHRC=yes
export RUNZSH=no

curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
sh install.sh
rm install.sh

rm "${ZSH}/lib/key-bindings.zsh"
touch "${ZSH}/lib/key-bindings.zsh"
cp ~/.config/zsh/kolo_custom.zsh-theme "${ZSH}/themes"

sudo mv "$ZSH" "$TARGET_PATH"
if uname -s | grep -q 'Darwin'; then
    sudo chown -R ole:everyone "$TARGET_PATH"
else
    sudo chown -R ole:ole "$TARGET_PATH"
fi
