#!/bin/bash
ZSH="${HOME}/.oh-my-zsh"
TARGET_PATH="/opt/oh-my-zsh"
ZSH_CUSTOM="/opt/oh-my-zsh-custom"
if [[ -d "${TARGET_PATH}" ]]; then
    exit 0
else
    echo installing oh my zsh
    export KEEP_ZSHRC=yes
    export RUNZSH=no
    curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh install.sh
    rm install.sh
    sudo mv $ZSH $TARGET_PATH
    sudo chown -R ole:ole $TARGET_PATH

    sudo mkdir -p $ZSH_CUSTOM/themes
    git clone https://github.com/reobin/typewritten.git
    sudo mv typewritten $ZSH_CUSTOM/themes
    sudo chown -R ole:ole $ZSH_CUSTOM
    ln -s "$ZSH_CUSTOM/themes/typewritten/typewritten.zsh-theme" "${TARGET_PATH}/themes/typewritten.zsh-theme"
fi
