#!/bin/bash
#IMAGE=~/.config/wallpaper/current_blur.png

#scrot -o "$IMAGE"
#convert "$IMAGE" -sample 20% -modulate 100,50 -scale 500% "$IMAGE"
#convert "$IMAGE" -sample 35% -scale 900% "$IMAGE"

#sleep 1 && xset +dpms &
#sleep 1 && xset dpms 15 30 3600 &
#sleep 5 && xset dpms force off &
#i3lock -n -t -i "$IMAGE"
#sleep 1 && xset dpms 0 0 0 &
#sleep 2 && xset s off -dpms &

env XSECURELOCK_SAVER=saver_mpv XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/.config/wallpaper -iname '*.mp4' -type f" XSECURELOCK_VIDEOS_FLAGS="--fs --panscan="1.0"" XSECURELOCK_BLANK_DPMS_STATE=off XSECURELOCK_AUTH_CURSOR_BLINK=0 XSECURELOCK_COMPOSITE_OBSCURER=0 XSECURELOCK_PASSWORD_PROMPT=hidden XSECURELOCK_SHOW_HOSTNAME=0 XSECURELOCK_SHOW_KEYBOARD_LAYOUT=0 XSECURELOCK_SHOW_USERNAME=0 XSECURELOCK_AUTH_TIMEOUT=5 xsecurelock


