#!/bin/bash
IMAGE=~/.config/wallpaper/current_blur.png
CONFIRM_FILE=~/.confirmsuspend
DO_SUSPEND=false

if [[ $1 == 'suspend' ]]; then
    DO_SUSPEND=true
elif [[ $1 == 'confirm' ]]; then
    touch "${CONFIRM_FILE}"
    i3-nagbar -t warning -m 'You pressed the suspend shortcut. Do you want to cancel?' -B 'Cancel suspend' 'lock_screen cancel' -B 'Suspend now' 'lock_screen now' &
    sleep 10

    if [[ -f ${CONFIRM_FILE} ]]; then
        rm "${CONFIRM_FILE}"
        pkill i3-nagbar
        DO_SUSPEND=true
    else
        pkill i3-nagbar
        exit 0
    fi
elif [[ $1 == 'cancel' ]]; then
    rm "${CONFIRM_FILE}"
    pkill i3-nagbar
    exit 0
elif [[ $1 == 'now' ]]; then
    rm "${CONFIRM_FILE}"
    pkill i3-nagbar
    DO_SUSPEND=true
fi

sleep 1 && xset +dpms &
sleep 1.5 && xset dpms 15 30 3600 &

if [[ $DO_SUSPEND == true ]]; then
    sleep 1 && systemctl suspend &
else
    sleep 5 && xset dpms force off &
fi

compositor_launch stop
compositor_launch start picom
compositor_launch start flashfocus

i3lock -n -t -i "$IMAGE"

compositor_launch start wallpaper

sleep 1 && xset dpms 0 0 0 &
sleep 2 && xset s off -dpms &

dv
