#!/bin/bash
if ! whoami | grep -q 'root'; then
    sudo mount_nas
else
    NAS_PATH=/home/ole/nas
    CRED_PATH=/etc/samba/credentials
    if [[ ! -f ${CRED_PATH}/usb_hdd ]]; then
        echo Run mount_nas_init && exit 1
    fi

    mkdir -p ${NAS_PATH}
    mount -t cifs //192.168.1.181/usb_hdd ${NAS_PATH} -o credentials=/etc/samba/credentials/usb_hdd,workgroup=WORKGROUP,uid=ole,vers=2.0
fi
