#!/bin/bash
type=${1}
project_name=${2}
build_name=${3}

oc project $project_name

if [ $type = 'spring' ]; then
    mkdir -p target/oc_spring/
    rm -rf target/oc_spring/
    mkdir -p target/oc_spring/
    cp -r config/spring/ target/oc_spring/deployments
    cp target/*.spring target/oc_spring/deployments

    oc start-build $build_name --from-dir=target/oc_jar --follow
elif [ $type = 'ng' ]; then
    mkdir -p target/oc_ng/
    rm -rf target/oc_ng/
    cp -r src/main/frontend/dist target/oc_ng/
    #cp config/ng/* target/oc_ng/
    oc start-build $build_name --from-dir=target/oc_ng/ --follow
fi
