#!/bin/bash
PROJ=${1}
SECRET_NAME=${2}
KEY_NAME=${3}
PASSK=${4}
PASSW=$(PASSWORD_STORE_DIR=~/code/.vipappspass pass show "$PASSK" | head -n 1)

oc project ${PROJ}
oc create secret generic ${SECRET_NAME} --from-literal=${KEY_NAME}=${PASSW}
