#!/usr/bin/env bash
set -eo pipefail

MISSING_COMMANDS=""

check_command_found() {
  if ! command -v "$1" >/dev/null 2>&1
  then
    MISSING_COMMANDS="${MISSING_COMMANDS}${1} "
  fi
}

check_yay_found() {
  if [[ -z "$(yay -Qs "$1")" ]]; then
    MISSING_COMMANDS="${MISSING_COMMANDS}${1} "
  fi
}

if [[ ! -z "$1" ]]; then
  check_command_found "$1"
  if [[ -z "$MISSING_COMMANDS" ]]; then
    exit 0
  else
    exit 1
  fi
fi

check_command_found "zsh"
check_command_found "git"
check_command_found "gh"
check_command_found "yadm"
check_command_found "pass"

check_command_found "vim"
check_command_found "nvim"

check_command_found "tmux"
check_command_found "sesh"
check_command_found "fzf"
check_command_found "zoxide"
check_command_found "rg"
check_command_found "cmake"

check_command_found "delta"
check_command_found "bat"

check_command_found "socat"
check_command_found "jq"
check_command_found "streamlink"

check_command_found "jdtls"
if [[ -z ${JAVA_HOME} || ! -d ${JAVA_HOME} ]]; then
  echo 'java home not set'
  exit 1
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  check_command_found "imgcat"
else
  check_yay_found "mpv-mpris"
fi

if [[ ! -z $MISSING_COMMANDS ]]; then
  echo "Missing commands: ${MISSING_COMMANDS}"
  exit 1
fi
