#!/bin/bash
source ~/.config/dots/zshrc.local

result=$(pass git pull && pass git push)

PASSV_DIR=~/code/.vipappspass
if [[ -d ${PASSV_DIR} ]]; then
    cd ${PASSV_DIR}
    git pull
    git push
fi

GIT_REMOTE_RESULT=$(git log HEAD..origin/main --oneline)
if [ ! -z "$(git status --porcelain)" ]; then 
  touch ~/.passsync_pending
elif [[ "${GIT_REMOTE_RESULT}" != "" ]] ; then
  touch ~/.passsync_pending
elif [[ -f ~/.passsync_pending ]]; then
  rm ~/.passsync_pending
fi

echo ${result}
