#!/usr/bin/bash
shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -lines 30 "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password"
else
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
        xdotool type --clearmodifiers --file -
fi

#pass_clear=$(pass show $password | head -n 1)
sleep 46 && clipmand --max-items=30 &
#sleep 47 && sed "s/\[\"${pass_clear}\"\]/\[\" \"\]/g;s/,\"${pass_clear}\"//g;s/\"${pass_clear}\",//g" ~/.local/share/clipman.json > ~/.local/share/clipman.json &
