#!/usr/bin/env bash
set -eo pipefail

branch="$1"

gitup -p .

if git branch -a | grep -q "$branch"; then
  git branch -D "$branch"
else
  echo "no branch '$branch' found"
  exit 0
fi

if git branch -a | grep "$branch" | grep -q origin; then
  git push origin ":$branch"
fi
