#!/usr/bin/env bash
set -eo pipefail

if [[ -z "$1" ]]; then
  branch="$(git branch --show-current)"
elif [[ "$1" = "update_only" ]]; then
  branch="$(git branch --show-current)"
  update_only="true"
else
  branch="$1"
fi
if [[ ! -z "$2" ]]; then
  base_branch="$2"
fi

if [[ "$branch" = "main" || "$branch" = "staging" || "$branch" = "production" || "$branch" = "trunc" ]]; then
  echo "Branch can not be main,staging,production,trunc"
  exit 0
fi

if ! git status --porcelain; then
  echo "Git status is not clean"
  exit 0
fi

gitup -p .

if [[ ! -z "$base_branch" ]]; then
  git checkout "$base_branch"
else
  git checkout staging || git checkout trunc || git checkout main || git checkout master
  base_branch="$(git branch --show-current)"
fi

git checkout "$branch"
git rebase "$base_branch"

if [[ -z "$update_only" ]]; then
  git checkout "$base_branch"
  git merge --no-edit --no-ff "$branch"

  git push origin "$base_branch"

  pr_delete "$branch"
fi
