#!/bin/bash
set -eo pipefail

branch="$1"
base_branch="$2"

if [[ "$1" = "main" || "$1" = "staging" || "$1" = "production" || "$1" = "trunc" ]]; then
  echo "Git status is not clean"
  exit 0
fi

if ! git status --porcelain; then
  echo "Git status is not clean"
  exit 0
fi

gitup -p .

if [[ ! -z "$base_branch" ]]; then
  git checkout "$base_branch"
else
  git checkout staging || git checkout trunc || git checkout main || git checkout master
  base_branch="$(git branch --show-current)"
fi

git checkout "$branch"
git rebase "$base_branch"

git checkout "$base_branch"
git merge --no-ff "$branch"

git push origin "$base_branch"

pr_delete "$branch"
