#!/usr/bin/env bash

NL=$'\n'

search_prs() {
    cd
    cd $2
    if [[ ! -f '.git/config' ]]; then
        return 0
    fi
    if cat '.git/config' | grep -q 'lht-general'; then
        SEARCH=$(gh pr list --search "$1")
        if [[ ! -z $SEARCH ]]; then
            if echo $SEARCH | grep -vq 'no pull_requests match'; then
                OUTPUT="${OUTPUT}${2}${NL}"
                OUTPUT="${OUTPUT}${SEARCH}${NL}"
            fi
        fi
    fi
}

check_prs() {
    OUTPUT="Open reviews:${NL}"
    for ghdir in $(gitup -l | tail -n +4); do search_prs "review-requested:@me" "${ghdir}"; done


    OUTPUT="${OUTPUT}${NL}My PRs:${NL}"
    for ghdir in $(gitup -l | tail -n +4); do search_prs "author:@me" "${ghdir}"; done
    printf "$OUTPUT"
}

(sleep 0.1 && tmux split-window) &
gitup > /dev/null &
check_prs
