#!/usr/bin/env bash

gitup > /dev/null &

checkPr() {
  repo="$(printf "$1" | jq -r '.repository.nameWithOwner')"
  repoName="$(printf "$1" | jq -r '.repository.name')"
  number="$(printf "$1" | jq -r '.number')"
  url="https://github.com/$repo/pull/$number"

  prInfo="$(gh pr view --json reviewRequests,reviewDecision,author,number,title,updatedAt $url)"
  author="$(printf "$prInfo" | jq -r '.author.name')"
  reviewDecision="$(printf "$prInfo" | jq -r '.reviewDecision')"
  title="$(printf "$prInfo" | jq -r '.title')"
  updatedAt="$(printf "$prInfo" | jq -r '.updatedAt')"
  if [[ "$author" = "Ole Hansen" ]]; then
    if [[ "$reviewDecision" = "APPROVED" ]]; then
      echo "Approved: $repoName - $number - $title - $updated"
    elif [[ "$reviewDecision" = "CHANGES_REQUESTED" ]]; then
      echo "Changes Requested: $repoName - $number - $title - $updated"
    fi
  else
    if [[ ! -z "$(printf "$prInfo" | jq -c '.reviewRequests[] | select( .login | contains("u898296"))')" ]]; then
      echo "To Review: $repoName - $number - $title - $updatedAt"
    fi
  fi
}

gh search prs --owner lht-general --involves @me --state open --sort updated --json number,repository | jq -c '.[]' | while read -r prItem; do checkPr "$prItem" ; done
