#!/bin/bash
source ~/.config/dots/proxy

echo "export http_proxy=\"http://localhost:3128\"" > ~/.config/dots/zshrc.local
echo "export no_proxy=\"${hold_no_proxy}\"" >> ~/.config/dots/zshrc.local
echo "export https_proxy=\"http://localhost:3128\"" >> ~/.config/dots/zshrc.local
echo "export ftp_proxy=\"http://localhost:3128\"" >> ~/.config/dots/zshrc.local
echo "export rsync_proxy=\"http://localhost:3128\"" >> ~/.config/dots/zshrc.local

cat ~/.config/dots/gitconfig.local.sample > ~/.config/dots/gitconfig.local
echo "  proxy = http://localhost:3128" >> ~/.config/dots/gitconfig.local
