#!/bin/bash
LHT_PING=$(/home/ole/.bin/lht_ping)

if [[ $(whoami) = 'root' ]]; then
    cat /etc/squid/squid.conf.base > /etc/squid/squid.conf
    if [[ $(echo ${LHT_PING} | grep 2) ]]; then
        cat /etc/squid/squid.conf.peer >> /etc/squid/squid.conf
    fi
else
    sudo sh -c "cat /etc/squid/squid.conf.base > /etc/squid/squid.conf"
    if [[ $(echo ${LHT_PING} | grep 2) ]]; then
        sudo sh -c "cat /etc/squid/squid.conf.peer >> /etc/squid/squid.conf"
    fi
fi

sudo systemctl restart squid
