#!/bin/bash
# crontab:
source ~/.config/dots/zshrc.local
note_dir=~/sync

cd ${note_dir}

result=$(git pull && git add . && (git diff-index --quiet HEAD || git commit -m 'ssync') && git push)

GIT_REMOTE_RESULT=$(git log HEAD..origin/main --oneline)
if [ ! -z "$(git status --porcelain)" ]; then 
  touch ~/.ssync_pending
elif [[ "${GIT_REMOTE_RESULT}" != "" ]] ; then
  touch ~/.ssync_pending
elif [[ -f ~/.ssync_pending ]]; then
  rm ~/.ssync_pending
fi

echo ${result}
