#!/bin/bash
set -eo pipefail

if ! tmux list-sessions | grep -q notes; then
  (notesync >/dev/null 2>&1) &
  tmux new-session -d -s notes > /dev/null

  tmux send-keys -t notes 'cd note && nvim "$(find . -type f | fzf)" && notesync && exit' Enter
fi

sesh connect notes
