#!/usr/bin/env bash

set -eo pipefail

CUR_DIR=$(pwd)
BASE_NAME=$(basename "${CUR_DIR}")

if [[ $BASE_NAME = 'ole' ]]; then
    if pgrep tmux; then
        tmux attach -t dotfiles || tmux att
    else
        if ! package_check; then
            sleep 5 && bash && exit 0
        fi

        w_ssh echo "Unlocked git key"
        pass -c stardom-world.com
        if [[ -f ~/.block_pass ]]; then
            rm ~/.block_pass
        fi

        tmux new-session -d -s background
        tmux send-keys -t background 'ghsync_d' Enter
        if package_check "cmuscontrold"; then
            tmux split-window -h -t background 'cmuscontrold'
        fi

        tmux new-session -d -s notes
        tmux send-keys -t notes 'vim ~/note/orga/inbox.txt' Enter

        tmux new-session -d -s dotfiles
        tmux send-keys -t dotfiles 'w_ssh yadm pull' Enter

        tmux new-session -d -s cmus

        tmux attach -t dotfiles
    fi
else
    tmux new-session -A -s "${BASE_NAME}" -c "$(pwd)"
fi
