#!/bin/bash
set -eo pipefail

if ! tmux list-sessions | grep -q notes; then
  tmux new-session -d -s notes > /dev/null

  tmux send-keys -t notes 'cd note && ((notesync >/dev/null 2>&1) & nvim orga/inbox.txt) && notesync && exit' Enter
fi

sesh connect notes
