#!/usr/bin/env bash
set -eo pipefail
BASE_NAME=$(basename $(pwd))
if [[ $BASE_NAME = 'ole' ]]; then
    if pgrep tmux; then
        tmux attach -t dotfiles
    else
        w_ssh echo "Unlocked git key"
        pass -c stardom-world.com

        tmux new-session -d -s background
        tmux send-keys -t background 'ghsync_d' Enter
        tmux split-window -h -t background 'cmuscontrold'

        tmux new-session -d -s notes
        tmux send-keys -t notes 'vim ~/note/orga/inbox.txt' Enter

        tmux new-session -d -s dotfiles
        tmux send-keys -t dotfiles 'w_ssh yadm pull' Enter

        tmux new-session -d -s cmus

        tmux attach -t dotfiles
    fi
else
    tmux new-session -A -s "${BASE_NAME}" -c "$(pwd)"
fi
