#!/bin/bash
set -eo pipefail

if ! tmux list-sessions | grep -q notes; then
  tmux new-session -d -s notes > /dev/null

  tmux send-keys -t notes 'cd note && nvim -c "Git pull" && notesync && exit' Enter
fi

sesh connect notes
