#!/usr/bin/env bash

set -eo pipefail

if [[ "$1" = "--legacy" ]]; then
  LEGACY_PEER_DEPS="true"
else
  ENV_ARGS="$1"
fi
if [[ "$2" = "--legacy" ]]; then
  LEGACY_PEER_DEPS="true"
fi

mkdir -p .dev

if [[ -f ".dev/docker_path" ]]; then
  DOCKER_FILE="$(cat .dev/docker_path)"
elif [[ -f "docker-compose.yml" ]]; then
  DOCKER_FILE="docker-compose.yml"
fi

SKIP_BUILD="false"
if [[ -f "pom.xml" ]]; then
  POMSUM="$(sha1 -q pom.xml)$(git rev-parse HEAD)"
  if [[ -f ".dev/pomxml" ]]; then
    LASTSUM=$(cat ".dev/pomxml")
    if [[ "$POMSUM" = "$LASTSUM" ]]; then
      SKIP_BUILD="true"
    fi
  fi
else
  SKIP_MAVEN="true"
fi

SKIP_PKG="false"
if [[ -f "src/main/frontend/package.json" ]]; then
  PKGJSON="src/main/frontend/package.json"
elif [[ -f "package.json" ]]; then
  PKGJSON="package.json"
else
  SKIP_NPM="true"
fi
if [[ ! -z "${PKGJSON}" ]]; then
  PKGSUM="$(sha1 -q ${PKGJSON})"
  if [[ -f ".dev/pkgjson" ]]; then
    LASTSUM=$(cat ".dev/pkgjson")
    if [[ "$PKGSUM" = "$LASTSUM" ]]; then
      SKIP_PKG="true"
    fi
  fi
fi

if [[ -z "$SKIP_MAVEN" && "$SKIP_BUILD" != "true" ]]; then
  mvn -T 1.1C clean package

  echo "$POMSUM" > ".dev/pomxml"
fi

if [[ -f "$DOCKER_FILE" && -z "$(docker-compose -f ${DOCKER_FILE} ps --services --filter 'status=running')" ]]; then
  docker-compose -f "${DOCKER_FILE}" up &
  DOCKER_STARTING="true"
fi

if [[ -z "$SKIP_NPM" && "$SKIP_PKG" != "true" ]]; then
  if [[ "$LEGACY_PEER_DEPS" = "true" ]]; then
    nf ci --legacy-peer-deps
  else
    nf ci
  fi
  echo "$PKGSUM" > ".dev/pkgjson"
fi

if [[ -f ".dev/mvn_extra_args" ]]; then
  MVN_EXTRA_ARGS="$(cat .dev/mvn_extra_args)"
fi

cleanupRun() {
  if [[ ! -z "$feId" ]]; then
    kill $feId
  fi
  if [[ ! -z "$beId" ]]; then
    kill $beId
  fi
  if [[ ! -z "$chromeId" ]]; then
    kill $chromeId
  fi
  if [[ -f ${DOCKER_FILE} ]]; then
    docker-compose -f "${DOCKER_FILE}" stop 
  fi
}

trap "cleanupRun" EXIT

if [[ -z "$SKIP_NPM" ]]; then
  nf run-script start &
  feId=$!
fi

if [[ "$DOCKER_STARTING" = "true" ]]; then
  while true; do
    sleep 1
    if [[ "$(docker-compose -f "$DOCKER_FILE" logs --since=90s | grep 'DATABASE IS READY TO USE!' | wc -l)" -gt 0 ]]; then
      break;
    elif [[ "$(docker-compose -f "$DOCKER_FILE" logs --since=90s | grep 'mariadbd: ready for connections' | wc -l)" -gt 0 ]]; then
      break;
    elif [[ "$(docker-compose -f "$DOCKER_FILE" logs --since=90s | grep 'MessageTypeServiceStart' | grep 'Done processing the packet of type' | wc -l)" -gt 0 ]]; then
      break;
    fi
  done
fi

if [[ -z "$SKIP_MAVEN" ]]; then
  if [[ -z $MVN_EXTRA_ARGS ]]; then
    (source read_idea_env "$ENV_ARGS" && mvn -T 1.1C spring-boot:run) &
  else
    (source read_idea_env "$ENV_ARGS" && mvn -T 1.1C spring-boot:run "${MVN_EXTRA_ARGS}") &
  fi
  beId=$!
fi

if [[ -z "$SKIP_MAVEN" ]]; then
  port_check "wait" "8080"
fi
if [[ -z "$SKIP_NPM" ]]; then
  angular_port="4200"
  if cat "$PKGJSON" | grep -q "port 4202"; then
    angular_port="4202"
  fi
  port_check "wait" "$angular_port"

  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --incognito --auto-open-devtools-for-tabs --user-data-dir="$HOME/.local/share/chrome_dev" "http://localhost:$angular_port" >/dev/null 2>&1 &
  chromeId="$!"
fi

wait
