#!/bin/bash
set -eo pipefail

if [[ -z "$1" ]]; then
  line="$(cat ~/note/media/twitch_vods.txt | head -n 20 | fzf)"
  link="$(awk '{print $1}' <<< $line)"
elif [[ $1 = https* ]]; then
  link="$1"
else
  link="https://www.twitch.tv/$1"
fi

quality="best"
if [[ ! -z "$2" ]]; then
  quality="$2"
fi

tmux new-window -n stream -t background: streamlink --ringbuffer-size=200M -p mpv -a '--cache=yes --cache-secs=3600 --demuxer-max-bytes=1000MiB ' "$link" "$quality"
