#!/bin/bash
set -eo pipefail

# in seconds POSITION=$(echo '{ "command": ["get_property_string", "time-pos"] }' | socat - /tmp/mpvstream | jq .data | tr '"' ' ' | cut -d'.' -f 1)

if [[ -z "$1" ]]; then
  line="$(cat ~/note/media/twitch_vods.txt | head -n 20 | fzf)"
  link="$(awk '{print $1}' <<< $line)"
  #seconds="$(echo "$link" | sed 's/.*\?t=')"
elif [[ $1 = https* ]]; then
  link="$1"
else
  link="https://www.twitch.tv/$1"
fi

quality="best"
if [[ ! -z "$2" ]]; then
  quality="$2"
fi

tmux new-window -n stream -t background: 
tmux send-keys -t background "vod_launch \"$link\" \"$quality\"" Enter
