#!/bin/bash
set -eo pipefail

link="vods"
quality="best"
cache="c3"

if [[ $1 = https* ]]; then
  cache="c0"
  link="$1"
elif [[ "$1" = "live" ]]; then
  link="live"
  cache="c0"
elif [[ "$1" = "combo" ]]; then
  link="combo"
elif [[ "$1" = "1080p" ]]; then
  quality="1080p60,1080p,720p60,720p,best"
elif [[ "$1" = "720p" ]]; then
  quality="720p,720p60,480p,best"
elif [[ "$1" = "420p" ]]; then
  quality="480p,worst"
elif [[ "$1" = "c0" || "$1" = "c1" || "$1" = "c2" || "$1" = "c3" ]]; then
  cache="$1"
elif [[ $1 = tok:* ]]; then
  link="https://www.tiktok.com/@$(echo $1 | cut -d ':' -f 2)"
elif [[ ! -z "$1" ]]; then
  cache="c0"
  link="https://www.twitch.tv/$1"
fi

if [[ "$2" = "await" ]]; then
  await_mode="true"
elif [[ "$2" = "1080p" ]]; then
  quality="1080p60,1080p,720p60,720p,best"
elif [[ "$2" = "720p" ]]; then
  quality="720p,720p60,480p,best"
elif [[ "$2" = "420p" ]]; then
  quality="480p,worst"
elif [[ "$2" = "c0" || "$2" = "c1" || "$2" = "c2" || "$2" = "c3" ]]; then
  cache="$2"
fi

if [[ "$3" = "c0" || "$3" = "c1" || "$3" = "c2" || "$3" = "c3" ]]; then
  cache="$3"
fi

ts_marker="$(date +"%H%M%S")"
vl_ts_marker=""
if [[ "$link" = "vods" ]]; then
  line="$(cat ~/note/media/twitch_vods.txt | head -n 30 | fzf)"
  link="$(awk '{print $1}' <<< $line)"

  if [[ $link != *youtu* ]]; then
    vl_ts_marker="$ts_marker"
  fi
elif [[ "$link" = "live" ]]; then
  line="$(vod_online picker | fzf)"
  link="$(awk '{print $1}' <<< $line)"
elif [[ "$link" = "combo" ]]; then
  tmp_picker_file="/tmp/vod_picker_opts"
  vod_online picker > $tmp_picker_file
  cat ~/note/media/twitch_vods.txt | head -n 30 >> "$tmp_picker_file"
  line="$(cat $tmp_picker_file | fzf)"
  link="$(awk '{print $1}' <<< $line)"
  rm "$tmp_picker_file"

  if [[ $link != *youtu* ]]; then
    if echo $line | grep -q 'is live on'; then
      cache="c0"
    else
      vl_ts_marker="$ts_marker"
    fi
  fi
fi

if [[ ! -z "$link" ]]; then
  if [[ ! -z "$await_mode" ]]; then
    vl_ts_marker="await"
  fi
  tmux new-window -n "stream$ts_marker" -t background: 
  tmux send-keys -t background "vod_launch \"$link\" \"$quality\" \"$cache\" \"$vl_ts_marker\" && exit || exit" Enter
fi
