#!/bin/bash
set -eo pipefail

if [[ "$3" = "c0" ]]; then
  rb_args="--ringbuffer-size=16M"
  cache_args="--cache=no"
elif [[ "$3" = "c1" ]]; then
  rb_args="--ringbuffer-size=200M"
  cache_args="--cache=yes --cache-secs=600 --demuxer-max-bytes=400MiB --demuxer-max-back-bytes=100MiB"
elif [[ "$3" = "c2" ]]; then
  rb_args="--ringbuffer-size=500M"
  cache_args="--cache=yes --cache-secs=1800 --demuxer-max-bytes=750MiB --demuxer-max-back-bytes=150MiB"
else
  rb_args="--ringbuffer-size=1000M"
  cache_args="--cache=yes --cache-secs=3600 --demuxer-max-bytes=1250MiB --demuxer-max-back-bytes=250MiB"
fi

socket_args=""
if [[ ! -z "$4" ]]; then
  mpv_socket="/tmp/mpv_${4}_stream"
  socket_args=" --input-ipc-server=$mpv_socket"
  tmux split-window -v -t background vod_ts "$1" "$mpv_socket"
  tmux last-pane -t background
fi

waitForYtStartup() {
  ytstarted="false"
  if [[ $1 = *?t=* ]]; then
    seek_to="$(echo $1 | sed 's/.*?t=//g')"
  fi
  while true
  do
    if ps ax | grep -v grep | grep mpv | grep -q 'no-ytdl'; then
      if [[ "$ytstarted" = "true" ]]; then
        sleep 5
      else
        ytstarted="true"
        if [[ "$seek_to" ]]; then
          sleep 1
          mpvYtSock="$(ps ax | grep mpv | grep -v grep | grep no-ytdl | sed 's/.*input-ipc-server=//g')"
          echo "{ \"command\": [ \"seek\", \"$seek_to\", \"absolute\" ] }" | socat - "$mpvYtSock"
        fi
      fi
    elif [[ "$ytstarted" = "true" ]]; then
      exit 0
    fi
    sleep 1
  done
}

if [[ $1 = *youtu* ]]; then
  yt playurl "$1" &
  waitForYtStartup "$1"
  exit 0
else
  streamlink "$rb_args" -p mpv -a "$cache_args $socket_args" "$1" "$2"
fi
