#!/bin/bash
set -eo pipefail

socket_args=""
if [[ ! -z "$3" ]]; then
  mpv_socket="/tmp/mpv_${3}_stream"
  socket_args=" --input-ipc-server=$mpv_socket"
  tmux split-window -v -t background vod_ts "$1" "$mpv_socket"
  tmux last-pane -t background
fi

streamlink --ringbuffer-size=1000M -p mpv -a "--cache=yes --cache-secs=3600 --demuxer-max-bytes=1250MiB --demuxer-max-back-bytes=250MiB $socket_args" "$1" "$2"

if [[ -z "$mpv_socket" ]]; then
  tmux kill-window
fi
