#!/bin/bash
set -eo pipefail

sudo systemctl start docker
sudo systemctl start docker.socket

if [[ "$1" = "-f" ]]; then
  echo 'remove all images and volumes'
  sudo docker system prune -f -a --volumes
else
  echo 'remove all dangling images'
  sudo docker system prune -f
fi

sudo systemctl stop docker
sudo systemctl stop docker.socket
