#!/bin/bash
path=$(pwd)
dir="${path}/${1}"
cdir="${path}/.${1}"
zex_dir="${cdir}/.zextract"

zex_init=$(ls "${zex_dir}")
if [[ -z $zex_init ]]; then
    echo 'zextract not initialized'
    exit;
fi

zex_state=$(cat "${zex_dir}/state")
if [[ $zex_state == 'open' ]]; then
    echo 'project already open'
    exit;
fi

mv "${cdir}" "${dir}"
sh "${dir}/.zextract/up.sh"
